# Generated by Django 5.0.2 on 2024-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr_app', '0002_task_assigned_to_task_due_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_days',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='repeats',
            field=models.BooleanField(default=True),
        ),
    ]
